services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: es-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # セキュリティを無効化
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
  db:
    image: mysql:8.0
    volumes:
      - db-store2:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=monorepo
      - MYSQL_ROOT_PASSWORD=monorepo1234
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

volumes:
  db-store2:
